### PR TITLE
🐛 Ensure passing correct endPattern

### LINKED ISSUE #1051: _wrapBy ignores args['after'] if no selection
## Problem

I'm using a custom command based on instructions from another issue. This works fine on selected text. But when there's no text selected, I get the "before" pattern twice, i.e. expect 「」but get「「

```
    {
        "key": "ctrl+[",
        "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown'",
        "command": "markdown.extension.editing._wrapBy",
        "args": {
            "before": "「",
            "after": "」"
        }
    },
```

## Environment

Markdown All in One v3.4.0

### PR DESCRIPTION
**Pull request by King-of-Infinite-Space**
fix #1051 
I'm assuming `wrapRange` calculates correctly when start and end patterns have different length

### CODE REVIEW

**Comment by yzhang-gh** [comment]
Thanks. LGTM

**Review by yzhang-gh — APPROVED** [review]

**Comment by Lemmingh** [comment]
@yzhang-gh

I find the calls to `getContext()` quite strange.

Do you remember the reason?

**Comment by yzhang-gh** [comment]
I cannot find the original issue.

It is a feature that works like this

```
foo |            <- ctrl+b
foo **|**
foo **bold|**    <- ctrl+b ⭐
foo **bold**|
foo **bold** bar|
```

And it is also used to remove empty surroundings like `**|**` as some of the `start/endPattern`s are not captured by the auto word selection(?)

**Comment by Lemmingh** [comment]
So, these scary chunks combine several features?

## Mimicking the on-off behavior of rich text editors and word processors

```markdown
foo **word|**
foo **word**|
```

Designed for **bold** and *italic*.

Discussed in #1.

Introduced in v0.5.0 (b1fd2e9a1c60153d2959ac6bf88a435f394e04d5) at 9dce8c8665ebc64ecbf485280987bfee24fec59a (#1).

## Toggling when the cursor is surrounded by white space or just the delimiters

```markdown
foo |
foo **|**
foo |
```

Designed for everything.

Discussed in #1.

Introduced in v0.5.0 (b1fd2e9a1c60153d2959ac6bf88a435f394e04d5) at e7a5e34153d95e63732c0e68bfcb9ac79696ab38.

## Quick styling: Toggling on a word without selecting it

```markdown
foo word|
foo **word**|
foo word|
```

Designed for everything.

Discussed in #19.

Introduced as optional feature in v0.8.0 (4f1beeda970c5c6dbb16899495395e8457b7b68c) via multiple commits.

Released as normal feature in v1.4.0 (a4fd09161d9415f98167f46ec933f2179ad4f691) at 3fae39c7069060625c3f226a603a1c9f58bf5fb7.

---

If so, we can have more clean-up here.

**Comment by yzhang-gh** [comment]
I think this covers all the use cases 👍

**Review by yzhang-gh — APPROVED** [review]
:shipit:

**Pull request merged**
