### PR TITLE
Adds KaTeX mhchem extension

### LINKED ISSUE #520: [Feature request] Adds KaTeX mhchem extension
https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem

This extension adds `\ce` and `\pu` functions to KaTeX, which are used to generate mechanical formulas and physical units.

Demo: https://mhchem.github.io/MathJax-mhchem/

### PR DESCRIPTION
**Pull request by balthild**
Closes #520 

Preview

### CODE REVIEW

**Comment by yzhang-gh** [comment]
Thank you. Will have a look soon.

**Comment by yzhang-gh** [comment]
I can confirm it works.

It is interesting this feature only needs a single `require`. Do you have any idea why it works? It seems to have defined some macros.

**Comment by balthild** [comment]
Yes. The script (https://github.com/KaTeX/KaTeX/blob/master/contrib/mhchem/mhchem.js) exports nothing but calls `katex.__defineMacro()` directly, which adds a macro globally regardless of katex options.

**Comment by yzhang-gh** [comment]
👍

**Pull request merged**
