### PR TITLE
issue #397 solved by porting django's link regexp.

### PR DESCRIPTION
**Pull request by Ovsyanka**
I plan to make additional change to store created regexp in [ExtensionContext.globalState](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage) to not compose it in each function call. Is it the appropriate way?

### CODE REVIEW

**Comment by yzhang-gh** [comment]
To me they are for "data" storage rather than runtime variables.

I think `util.ts` is a better place, like this

https://github.com/yzhang-gh/vscode-markdown/blob/214236bf4b158d73b39649b440c79178ea674c15/src/util.ts#L11

**Comment by Ovsyanka** [comment]
Отправлено с моего устройства HuaweiAs you say so =) I'll do it tomorrow.Could you please check my changes? Is it ready to be accepted? Maybe something you prefer to be done differently? -------- Исходное сообщение --------Тема: Re: [yzhang-gh/vscode-markdown] [WIP] issue #397 solved by porting django's link regexp. (#401)От: Yu Zhang Кому: yzhang-gh/vscode-markdown Копия: Igor ,Author To me they are for "data" storage rather than runtime variables.
I think util.ts is a better place, like this
https://github.com/yzhang-gh/vscode-markdown/blob/214236bf4b158d73b39649b440c79178ea674c15/src/util.ts#L11

**Comment by yzhang-gh** [comment]
Looks awesome to me, thanks 👍. We can merge in when you get it done.

**Comment by Ovsyanka** [comment]
Actually I think that it is quite different tasks, so better to do it in separate PR. Some more questions could arise and I don't like to delay this PR because of them.

**Comment by yzhang-gh** [comment]
I know. What you expect is the[ singleton pattern](https://en.wikipedia.org/wiki/Singleton_pattern). `const` should be enough. And placing in `formatting.ts` is also fine.

**Comment by yzhang-gh** [comment]
Thanks for your great work! 🍻

**Pull request merged**
