### PR TITLE
#151 fix using `grapheme-splitter` for text shinkage

### PR DESCRIPTION
**Pull request by CircleOnCircles**
#151 fix using `grapheme-splitter`

### CODE REVIEW

**Comment by CircleOnCircles** [comment]
It passes all the tests related to the table.

**Comment by yzhang-gh** [comment]
I am going to make some changes to it. Do you have some Thai code snippets for testing?

**Comment by CircleOnCircles** [comment]
Here is the sample
```
| คุณครู | รั้วริม | ไอ้หนูน้อย |
| --- | --- | --- |
| Teacher | The border | kids |
```

```
| คุณครู    | รั้วริม       | ไอ้หนูน้อย |
| ------- | ---------- | ------- |
| Teacher | The border | kids    |
```

**Comment by yzhang-gh** [comment]
Thank you!

**Comment by yzhang-gh** [comment]
Now it should be properly fixed. You can try it out using the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by CircleOnCircles** [comment]
Sound great! 😄

**Comment by CircleOnCircles** [comment]
Tested. It works as expected. 🎉

**Pull request merged**
