### PR TITLE
Added: more greek letters

### PR DESCRIPTION
**Pull request by upupming**
See https://github.com/upupming/docsify-katex/blob/master/docs/supported.md#letters-and-unicode

### CODE REVIEW

**Comment by yzhang-gh** [comment]
Thanks. Would you mind also updating the other KaTeX functions?

**Comment by upupming** [comment]
Of course, I will do that!

**Comment by upupming** [comment]
I am updating all symbols available at https://github.com/KaTeX/KaTeX/blob/master/docs/supported.md.

**Comment by upupming** [comment]
Used regex on https://regexr.com/:
1. `\$\\([^\s]|[^\$]*)\$`
2. `\{([^\{\}]*)\}` For those with `{}`
3. `\~\\([^,]*)\'` (for `delimiters0`)
4. For `delimeterSizing0`
 ```
\`\\([^`]*)\`
```

... And some hand editting.

Also added some new array, do I need to update the code dealing with them?

**Comment by yzhang-gh** [comment]
Thanks for the effort! And sorry for being slow to respond. I have been busy for a while.

> Also added some new arrays, do I need to update the code dealing with them?

Sure. Just tell me when it is ready to merge.

**Comment by upupming** [comment]
@yzhang-gh Thanks for the review, I will fix them ASAP.

**Comment by upupming** [comment]
Don't know why I have added `Epsilon` but it will not autocomplete, And that completion of `text{\P}` will add a redundant `}`
vs-md-tex-com

Could you please explain why this happens?

**Comment by yzhang-gh** [comment]
Will take a look this weekend

**Comment by yzhang-gh** [comment]
I have merged your branch. (deleted unusual functions like `\text{\OE}` and `\text{\textunderscore}`)

Many thanks.

**Comment by upupming** [comment]
This is really a whole batch of work, thanks for your help.

**Comment by upupming** [comment]
Just an advertisement, you can use https://github.com/PicGo/bump-version for better workflow if you would like, haha!

**Comment by upupming** [comment]
I will test and report soon.

**Comment by upupming** [comment]
Works perfectly, thanks again sir!

**Pull request closed without merging**
