### PR TITLE
add toggle code block

### PR DESCRIPTION
**Pull request by axiqia**
Add toggle code block and shortcut bind with `ctrl+shift+k`.

### CODE REVIEW

**Comment by haakonstorm** [comment]
Awesome! Yes, please add.
For now I have a bettertouchtool workflow who copies to clipboard then adds and pastes back, but better to have it natively. With some sanity checking.

**Comment by yzhang-gh** [comment]
Thanks for your contribution 👍

However, I would not like to make "toggle code block" the same as "toggle bold/italic" as the later is an inline operation and supports multi-cursors.

multi-cursors

https://github.com/yzhang-gh/vscode-markdown/blob/b845a4a87a9e7e190980e1dd55d7cc1252818a9e/src/formatting.ts#L309

Of course, we can add more `if-else` to make it also work for "code block". But I think it would be an overkill.

I prefer to add a separate command which does `vscode.commands.executeCommand('editor.action.insertSnippet', ...)`. It is simple but just fits our needs.

As for the keybinding, I suggest letting users decide, just like the other "toggle" commands.

https://github.com/yzhang-gh/vscode-markdown/blob/14fc9e43f1a4a7ae6d2c39e4b23115f11fca9084/package.json#L47-L66

**Comment by axiqia** [comment]
Firstly, maybe we should reach a consensus on this feature and decide whether to have this feature or not.  While it is simple to use snippets to toggle code blocks,  as @haakonstorm said, it is better to have it natively. 

Secondly, I confess I wrote ugly codes. I'm just lazy to reuse the previous code. I can reorganize the code.

For the keybinding, of course,  it should let users decide.

**Comment by yzhang-gh** [comment]
> Firstly, maybe we should reach a consensus on this feature and decide whether to have this feature or not.

Of course, I'm fine with this feature.

> In my opinion, toggling code blocks don't support multi-cursors.

I agree.

We can just add a new command `toggleCodeBlock` which executes `editor.action.insertSnippet` internally, so that users don't need to add the snippet themselves.

**Comment by yzhang-gh** [comment]
🍻

**Comment by yzhang-gh** [comment]
I've made a few changes. Users need to assign a keybinding to the new command `toggleCodeBlock`, just like what we do for `toggleCodeSpan` and `toggleList`.

It should be available in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) now.

**Comment by axiqia** [comment]
@yzhang-gh 🍻

**Comment by sunknudsen** [comment]
@axiqia Thanks for the PR. How is `toggleCodeBlock` enabled?

**Pull request merged**
