### PR TITLE
🐛 Set `vscode-dark` class when exporting with dark theme

### PR DESCRIPTION
**Pull request by raphaelsander**
Hi,

When the theme dark is selected on configuration, the code block don't showing the dark theme.
This commit fix it.

### CODE REVIEW

**Comment by Lemmingh** [comment]
Could you elaborate on your findings?

I don't see relevant changes in VS Code's `markdown.css` since 2019-10-13 (#534).

**Comment by yzhang-gh** [comment]
There does exist `vscode-dark` selectors in https://github.com/microsoft/vscode/blob/79d9bb8754331225372e892393619d4072474a19/extensions/markdown-language-features/media/markdown.css#L214 so this PR looks fair enough.

**Review by yzhang-gh — APPROVED** [review]
LGTM

**Comment by Lemmingh** [comment]
The failed test is irrelevant. Not sure what caused it. Maybe we need to avoid such flaky checks.

**Comment by yzhang-gh** [comment]
Thank both of you 👍

> The failed test is irrelevant. Not sure what caused it. Maybe we need to avoid such flaky checks.

That is weird. Anyway, let's merge this PR in and see whether the CI is okay.

**Pull request merged**
