### PR TITLE
Add gitea slugification

### PR DESCRIPTION
**Pull request by rodolpheh**
When generating TOC, the links are not properly slugified for Gitea. One of the issues I had was that Gitea expect all underscores to be hyphen.

**This is a quick hack, I'm still missing the source for the slugification function of Gitea so I'm not sure all the proper changes are made when slugifying. Also the tests probably doesn't cover every cases.**

### CODE REVIEW

**Comment by yzhang-gh** [comment]
Thanks for the PR.

I'm okay with this as you already implemented it. As for the failed test, you can make a document
containing heading `# foo & < >  "foo"` and see what anchor Gitea will generate.

**Comment by rodolpheh** [comment]
Sorry for the forced push, I was trying to hide my mistakes... Anyway, the tests are shown as not okay, but I tried triggering them on my repository and everything is okay. I don't know if you can run them again.

**Comment by rodolpheh** [comment]
Mmh the tests keep failing on this repository. See the pull request on my fork : https://github.com/rodolpheh/vscode-markdown/pull/4

**Comment by yzhang-gh** [comment]
Well, that's strange. Let me just merge it in.

**Comment by yzhang-gh** [comment]
All set. 🍻

**Comment by rodolpheh** [comment]
For future references, I think that gitea uses blackfriday for parsing and sanitizing the markdown, [here is an explanation of the algorithm used for anchor sanitation in blackfriday](https://godoc.org/github.com/russross/blackfriday#hdr-Sanitized_Anchor_Names).

**Comment by Lemmingh** [comment]
Gitea has migrated to [goldmark](https://github.com/yuin/goldmark) with their own slugify method since version 1.11 released on 2020-02-10.

* <https://docs.gitea.io/en-us/faq/#why-is-my-markdown-broken>

  > goldmark for Markdown rendering

* <https://pkg.go.dev/code.gitea.io/gitea/modules/markup/markdown?tab=imports>

* go-gitea/gitea#9533

* <https://github.com/yuin/goldmark/blob/bd58441cc141c6455d2ed592a4f1d01adee4211a/README.md#context-options>

  > `IDs` allows you to change logics that are related to element id (ex: Auto heading id generation).

* <https://github.com/yuin/goldmark/issues/56#issuecomment-562963529>

---

I hope the info above is useful to you.

**Comment by yzhang-gh** [comment]
> Gitea has migrated to [goldmark](https://github.com/yuin/goldmark) with their own slugify method since version 1.11 released on 2020-02-10.

👍. Just to leave a reminder for myself here, Hugo also uses goldmark (https://github.com/yzhang-gh/vscode-markdown/issues/689#issuecomment-631424950).

**Comment by rodolpheh** [comment]
Woah this is great information, thank you very much. For now, I have improved the gitea slugification to follow more closely the blackfriday algorithm (see https://github.com/yzhang-gh/vscode-markdown/pull/764). It seems to work with a few exotic values and hopefully will work for most of the cases.

**Comment by rodolpheh** [comment]
For reference and if I'm not mistaken, this is the default goldmark function called for generating the IDs :
https://github.com/yuin/goldmark/blob/master/util/util.go#L517

**Pull request merged**
