### PR TITLE
macros settings need a deep copy

### LINKED ISSUE #455: No option for max table width
#### What is the problem?
Not possible to set max width on table format.

Example, when formatting a table like this:

```text
| H1                | H2                                  | H3  |
| :------------- | :------------------------- | :---- |
| Bar                | Some very<br>long line of<br>text Some very<br>long line of<br>textSome very<br>long line of<br>text Some very<br>long line of<br>text | Foo |
```
it will format it into something like this:

```text
| H1                 | H2                                                                                                                                     | H3  |
| :----------------- | :------------------------------------------------------------------------------------------------------------------------------------- | :-- |
| Bar                | Some very<br>long line of<br>text Some very<br>long line of<br>textSome very<br>long line of<br>text Some very<br>long line of<br>text | Foo |
```

I would like a setting to set the max amount of dashes ("-" in "| :--- |") since Pandoc will use number of dashes to set the rendered table width in html.

### PR DESCRIPTION
**Pull request by upupming**
#445

Don't know why but I just copied the default macros of `\\\\` and now it works.
https://github.com/KaTeX/KaTeX/blob/c8f2783ca82b48edda1673dffabcf99f55f8bb7f/src/macros.js#L673

### CODE REVIEW

**Comment by yzhang-gh** [comment]
Thank you. It seems that KaTeX has some built-in macros when the option is enabled.

I decide to only enable `macros` option when the user explicitly set it. (Otherwise, there may be other potential issues if there are still other built-in macros we haven't noticed)

I will make a few changes on my side. Let's see whether it works.

**Comment by upupming** [comment]
I now know where the problem comes from. It seems `workspace.getConfiguration` return a reference to the configuration settings which is not modifiable (or not be modifying as expected). But [katex says](https://katex.org/docs/options.html) they will modify the `macros` object during initializing.
We have to [make a deep copy](https://stackoverflow.com/a/5344074/8242705) of that object instead of directly use it:

```js
macros: {}
```
is not equal to:
```js
macros: workspace.getConfiguration('markdown.extension.katex').get<object>('macros'))
```

**Comment by upupming** [comment]
早知道上次直接复制 `markdown+math` 的做法就对了 😅

**Comment by yzhang-gh** [comment]
有道理，我这里改一下

**Comment by yzhang-gh** [comment]
Thank you!

**Pull request merged**
